### ISSUE TITLE
Use local package.json information

### ISSUE THREAD

**Issue by cgatian** [mainawycliffe/npm-imported-packages-lens#5]
Looking at the source the packages Urls are resolved by fetching data from NPM. Isn't this same data available in the `package.json` of the package?

Just curious if there was a reason that wasn't used? Perhaps you can't read files from an extension?

**Comment by mainawycliffe** [comment]
@cgatian sorry, I missed this issue. I hadn't thought of this actually; this would be a good idea actually; start with the info on `node_modules` and fallback to NPM API if the user hasn't run `yarn install`.

**Comment by mainawycliffe** [comment]
I have been playing with this, and it's proving to be an interesting challenge in some edge cases. On most workspaces, we have a single node_modules, and in this case, it's a matter of finding it and checking if the package we want, and retrieving info from package.json. However in cases with nested multiple node_modules, this is a little tricky, as you need to find the neared node_module and get package.json from it.

**Comment by cgatian** [comment]
Yeah. I don't think it's a good idea. The package information could be stale, so retrieving it straight from npm is the best way.  I originally was thinking about this because at the company I work for
